Repository coupong-wowdeal/coupong-wowdeal, pull requests merged in 2024-07, with the labels that each got.

#23 ✨ 유저 도메인 추가 및 기본 설정
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/user/controller/v1/UserController.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/user/model/v1/User.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/user/model/v1/UserRole.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/user/repository/v1/UserRepository.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/user/service/v1/UserService.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/infra/security/SecurityConfig.kt
Labels: 기능

#25 ➕ QueryDsl 의존성 추가
  build.gradle.kts
  src/main/kotlin/coupong/nbc/coupongwowdeal/infra/querydsl/QueryDslConfig.kt
Labels: 기능

#24 :sparkles: JWT 기본적인 인증 인가 및 Swagger 설정 추가
  build.gradle.kts
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/user/controller/v1/UserController.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/user/dto/v1/response/SignInResponse.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/user/dto/v1/response/TokenCheckResponse.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/user/service/v1/UserService.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/exception/dto/ErrorDto.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/infra/security/CustomAuthenticationEntrypoint.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/infra/security/SecurityConfig.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/infra/security/UserPrincipal.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/infra/security/jwt/JwtAuthenticationFilter.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/infra/security/jwt/JwtAuthenticationToken.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/infra/security/jwt/JwtPlugin.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/infra/swagger/SwaggerConfig.kt
Labels: 기능

#27 ✨ Coupon 도메인 추가 및 기본 설정
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/controller/v1/CouponController.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/dto/CouponResponse.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/dto/CreateCouponRequest.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/model/v1/Coupon.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/model/v1/CouponUser.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/repository/v1/CouponRepository.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/repository/v1/CouponRepositoryCustom.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/repository/v1/CouponRepositoryImpl.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/service/v1/CouponService.kt
Labels: 기능

#30 :sparkles: User CRUD API 추가
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/user/controller/v1/UserController.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/user/dto/v1/request/SignInRequest.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/user/dto/v1/request/SignUpRequest.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/user/dto/v1/response/UserResponse.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/user/repository/v1/UserRepository.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/user/service/v1/UserService.kt
Labels: 기능

#31 :sparkles: GlobalExceptionHandler 추가
  src/main/kotlin/coupong/nbc/coupongwowdeal/exception/AccessDeniedException.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/exception/GlobalExceptionHandler.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/exception/ModelNotFoundException.kt
Labels: 기능

#32 :sparkles: 핵심 Entity Auditing 추가
  src/main/kotlin/coupong/nbc/coupongwowdeal/CoupongWowdealApplication.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/common/AuditorAwareUserId.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/common/BaseAuditingEntity.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/common/BaseTimeEntity.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/model/v1/Coupon.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/timedeal/model/v1/TimeDeal.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/user/model/v1/User.kt
Labels: 기능

#34 ✨ Coupon 도메인 CRUD 기능 구현
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/controller/v1/CouponController.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/dto/CouponResponse.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/dto/CreateCouponRequest.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/model/v1/Coupon.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/model/v1/CouponUser.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/repository/v1/CouponQueryDslRepository.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/repository/v1/CouponRepository.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/repository/v1/CouponRepositoryCustom.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/repository/v1/CouponRepositoryImpl.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/repository/v1/coupon/CouponJpaRepository.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/repository/v1/couponuser/CouponUserJpaRepository.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/service/v1/CouponService.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/service/v1/CouponServiceImpl.kt
Labels: 기능

#38 ✨ 만료된 쿠폰 삭제 스케줄러 구현
  src/main/kotlin/coupong/nbc/coupongwowdeal/CoupongWowdealApplication.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/controller/v1/CouponController.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/dto/CouponResponse.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/model/v1/Coupon.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/model/v1/CouponUser.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/repository/v1/CouponQueryDslRepository.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/repository/v1/CouponRepository.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/repository/v1/CouponRepositoryImpl.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/service/v1/CouponService.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/service/v1/CouponServiceImpl.kt
Labels: 기능

#40 :sparkles: 타임딜 + 쿠폰 생성, 발급 CRUD
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/common/BaseTimeEntity.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/controller/v1/CouponController.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/dto/CouponInfoResponse.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/dto/CouponResponse.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/dto/CreateCouponRequest.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/model/v1/Coupon.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/model/v1/CouponUser.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/repository/v1/CouponRepository.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/repository/v1/CouponRepositoryImpl.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/repository/v1/couponuser/CouponUserJpaRepository.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/service/v1/CouponService.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/service/v1/CouponServiceImpl.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/timedeal/controller/v1/TimeDealController.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/timedeal/dto/request/CreateTimeDealRequest.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/timedeal/dto/request/UpdateTimeDealRequest.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/timedeal/dto/response/TimeDealCouponResponse.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/timedeal/dto/response/TimeDealResponse.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/timedeal/model/v1/TimeDeal.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/timedeal/repository/v1/TimeDealJpaRepository.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/timedeal/repository/v1/TimeDealRepository.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/timedeal/repository/v1/TimeDealRepositoryImpl.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/timedeal/service/v1/TimeDealService.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/timedeal/service/v1/TimeDealServiceImpl.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/exception/GlobalExceptionHandler.kt
Labels: 기능

#42 ✨ redis lock을 이용한 스케줄러 동시성 제어
  build.gradle.kts
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/service/v1/CouponServiceImpl.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/infra/redis/EmbeddedRedisConfig.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/infra/redis/LockService.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/infra/redis/RedisConfig.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/infra/redis/RedisLockRepository.kt
  src/test/kotlin/coupong/nbc/coupongwowdeal/infra/redis/LockServiceTest.kt
Labels: 기능

#43 :white_check_mark: Coroutine 동시성 테스트
  src/test/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/service/CouponServiceDBTest.kt
Labels: 기능

#45 :white_check_mark: 쿠폰 발급 동시성 테스트 코드 추가
  src/test/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/service/CouponServiceDBTest.kt
Labels: 기능

#46 :sparkles: 쿠폰 발급 Redis Lock으로 동시성 제어
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/service/v1/CouponServiceImpl.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/exception/EmptyQuantityException.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/infra/redis/LockService.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/infra/redis/RedisLockRepository.kt
  src/test/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/service/CouponServiceDBTest.kt
Labels: 기능

#47 :sparkles: Lock AOP로 적용하게 수정
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/common/aop/Lock.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/common/aop/SpinLock.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/common/aop/Transactional.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/service/v1/CouponServiceImpl.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/infra/redis/LockService.kt
  src/main/kotlin/coupong/nbc/coupongwowdeal/infra/redis/RedisLockRepository.kt
  src/test/kotlin/coupong/nbc/coupongwowdeal/domain/coupon/service/CouponServiceDBTest.kt
  src/test/kotlin/coupong/nbc/coupongwowdeal/infra/redis/LockServiceTest.kt
Labels: 기능

#49 :sparkles: 부하 테스트를 위한 DataInitializer
  build.gradle.kts
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/common/initializer/DataInitializer.kt
Labels: 기능

#52 🐛 redis lock 사용시 동시성 문제 해결
  src/main/kotlin/coupong/nbc/coupongwowdeal/domain/timedeal/service/v1/TimeDealServiceImpl.kt
Labels: 버그

#53 :memo: README.md 작성
  README.md
  articles/@SpringBootTest 에서 생성자에 Bean이 없으면 사용중인 Componet가 자동 주입되지 않는 이슈.md
  articles/Redisson 적용으로 성능 개선.md
  articles/Unlock과 Transactional Commit 사이의 Lock 획득 문제.md
  articles/각 Lock 방식 장단점 비교.md
  articles/낙관적 Lock으로 쿠폰 동시성 제어해보기.md
  articles/테스트 코드상에서 명시적인 @Transactional을 걸어야 호출중인 Service 로직 내의 더티체킹이 작동함.md
Labels: 문서

#55 📝 Readme 수정
  README.md
Labels: 문서
